apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  name: katib-game
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
    # additionalMetricNames:
    #   - Train-accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 7
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.06"
    # - name: num-layers
    #   parameterType: int
    #   feasibleSpace:
    #     min: "2"
    #     max: "5"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
          - ftrl
  trialTemplate:
    primaryContainerName: training-container1
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      # - name: numberLayers
      #   description: Number of training model layers
      #   reference: num-layers
      - name: optimizer
        description: Training model optimizer (sdg, adam or ftrl)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations: 
              sidecar.istio.io/inject: "false"
          spec:
            volumes:
              - name: training
                persistentVolumeClaim: 
                  claimName: create-volume1
            containers:
              - name: training-container1
                image: docker.io/729578/train:latest
                command:
                  - "python3"
                  - "/pipelines/component/src/train.py"
                  - "--data-path=$mount_path"
                  - "--batch-size=64"
                  - "--loss=crossentropy"
                  - "--metrics=accuracy"
                  - "--epochs=5"
                  - "--learning-rate=${trialParameters.learningRate}"
                  - "--optimizer=${trialParameters.optimizer}"
                volumeMounts:
                - mountPath: /mount/  
                  name: training
            restartPolicy: Never
