apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  name: tlt-training
spec:
  objective:
    type: minimize
    goal: 0.00001
    objectiveMetricName: loss
  algorithm:
    algorithmName: random
  parallelTrialCount: 1
  maxTrialCount: 1
  maxFailedTrialCount: 1
  parameters:
    - name: num_epochs
      parameterType: int
      feasibleSpace:
        min: "15"
        max: "50"
  trialTemplate:
    primaryContainerName: training
    trialParameters:
      - name: numEpochs
        description: number of epochs for training
        reference: num_epochs
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations: 
              sidecar.istio.io/inject: "false"
          spec:
            volumes:
              - name: training
                persistentVolumeClaim: 
                  claimName: dummy-name
            containers:
              - name: training
                image: nvcr.io/nvidia/tlt-streamanalytics:v3.0-py3
                command: 
                  - "echo starting;"
                  - "if [ -d  %s/experiment_dir_unpruned ]; then rm -Rf -v %s/experiment_dir_unpruned; fi ;"
                  - "export http_proxy=%s;"
                  - "export https_proxy=%s;"
                  - "export HTTP_PROXY=%s;"
                  - "export HTTPS_PROXY=%s;"
                  - "/usr/local/bin/install_ngc_cli.sh;"
                  - "wget https://raw.githubusercontent.com/aruvi198/Longest-common-sequence/master/modify.py;"
                  - "echo working on ;"
                  - "python3 modify.py --batch-size-per-gpu=%s --num-epochs=%s --regularizer=%s --spec-path=%s --new-spec-path=%s;"
                  - "%s train -e %s/specs/new_spec.txt -r %s/experiment_dir_unpruned -k %s -n %s "
                  - "echo ${trialParameters.numEpochs}"
                volumeMounts:
                - mountPath: /dummy/path
                  name: training
            restartPolicy: Never
